package br.gov.sp.campinas.cadcamp.enums;

public enum TipoImovel {

	DOMICILIO,
	COMERCIO,
	TERRENO_BALDIO,
	PONTO_ESTRATEGICO,
	ESCOLA,
	CRECHE,
	ABRIGO,
	INSTITUICAO_PERMANENCIA,
	UNIDADE_PRISIONAL,
	UNIDADE_SOCIO_EDUCATIVA,
	DELEGACIA,
	ESTABELECIMENTO_RELIGIOSO,
	OUTROS;
	
}
